language: bash
services: docker

script:
 - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
 - export REPO=nikolaev-rd/pinba-engine
 - docker build -t $REPO:$TAG -f Dockerfile .

after_script:
  - docker images
