language: bash
services: docker

addons:
  apt:
    packages:
      - mariadb-client

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=nikolaev-rd/pinba-engine

script:
 - export TAG=latest
 - export REPO=nikolaev-rd/pinba-engine
 - docker build -t $REPO:$TAG -f Dockerfile .

after_script:
  - docker images
  - docker run --rm $REPO:$TAG --name pinba --restart=on-failure:3
