language: bash
services: docker

env:
  global:
  - REPO=$TRAVIS_REPO_SLUG
  - TAG=$([ "$TRAVIS_BRANCH" = "master" ] && echo "latest" || echo "${TRAVIS_COMMIT::8}-${TRAVIS_JOB_NUMBER}")

script:
  - docker build -t $REPO:$TAG -f Dockerfile .

after_script:
  - docker images
