language: bash
services: docker

platform:
  - x64
  - x86

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=nikolaev-rd/pinba-engine

script:
  - export TAG=$([ ! -z "$TRAVIS_COMMIT" ] && echo "$TRAVIS_COMMIT" || echo "latest")
  - export REPO=nikolaev-rd/pinba-engine
  - docker build -t $REPO:$TAG -f Dockerfile .

after_script:
  - docker images
