language: bash
services: docker

platform:
  - x64
  - x86

env:
  global:
  - REPO=$TRAVIS_REPO_SLUG
  - TAG=$([ "$TRAVIS_BRANCH" = "master" ] && echo "$TRAVIS_JOB_NUMBER" || echo "${TRAVIS_COMMIT::8}")

script:
  - docker build -t $REPO:$TAG -f Dockerfile .

after_script:
  - docker images
